version: '3.8'

services:
  app:
    image: allsveam/talento:v1  # Imagen que construyes y subes a Docker Hub
    container_name: talento_app
    ports:
      - "8000:80"
    environment:
      APP_ENV: local
      APP_DEBUG: 0
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: academy_lms
      DB_USERNAME: root
      DB_PASSWORD: root_password
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: talento_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: academy_lms
    ports:
      - "3306:3306"
    volumes:
      - ./db_backup:/docker-entrypoint-initdb.d  # Si quieres restaurar un backup al crear la base
      #- db_data:/var/lib/mysql
